"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { Download, FileText, Loader2, Printer, BarChart3 } from "lucide-react";
import type { ExecutiveReport, RunState } from "@/lib/types";
import { fetchRun } from "@/lib/client/cache";
import { hostOf } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BrandedSpinner } from "@/components/shared/cinematic-loader";

function toMarkdown(r: ExecutiveReport, title: string): string {
  const li = (a: string[]) => a.map((x) => `- ${x}`).join("\n");
  return `# Ghost Customer AI — Executive Report
## ${title}

## Executive Summary
${r.executiveSummary}

## Key Findings
${li(r.keyFindings)}

## Conversion Risks
${li(r.conversionRisks)}

## Churn Risks
${li(r.churnRisks)}

## Revenue Leaks
${li(r.revenueLeaks)}

## Customer Questions
${li(r.customerQuestions)}

## Competitor Notes
${li(r.competitorNotes)}

## Recommendations
${r.recommendations.map((rec) => `### ${rec.title}\n${rec.detail}\n_Effort: ${rec.effort} · Impact: ${rec.impact}_`).join("\n\n")}

## Projected Impact
${r.projectedUplift}

---
_Generated by Ghost Customer AI — "The AI that becomes your customer before your customer becomes your problem."_
`;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card className="print-card">
      <CardHeader>
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent>{children}</CardContent>
    </Card>
  );
}

function Bullets({ items }: { items: string[] }) {
  if (!items.length) return <p className="text-sm text-muted-foreground">None.</p>;
  return (
    <ul className="space-y-2">
      {items.map((it, i) => (
        <li key={i} className="flex gap-2.5 text-sm text-slate-600">
          <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-ghost-violet" />
          {it}
        </li>
      ))}
    </ul>
  );
}

export function ReportView({ runId }: { runId: string }) {
  const [run, setRun] = useState<RunState | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchRun(runId).then((r) => {
      setRun(r);
      setLoading(false);
    });
  }, [runId]);

  if (loading)
    return (
      <div className="container flex min-h-[60vh] items-center justify-center py-28">
        <BrandedSpinner label="Compiling your executive report…" />
      </div>
    );

  if (!run?.report)
    return (
      <div className="container flex min-h-[60vh] flex-col items-center justify-center gap-4 py-28 text-center">
        <p className="text-lg font-semibold">No report found for this run.</p>
        <Link href="/dashboard">
          <Button>Run a new simulation</Button>
        </Link>
      </div>
    );

  const r = run.report;
  const title = run.analysis?.title ?? hostOf(run.config.url);

  function downloadMd() {
    const blob = new Blob([toMarkdown(r, title)], { type: "text/markdown" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = `ghost-report-${hostOf(run!.config.url)}.md`;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  return (
    <div className="container max-w-4xl py-24">
      <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <Link href={`/insights/${runId}`}>
            <Button variant="ghost" size="sm">
              <BarChart3 className="h-4 w-4" /> Insights
            </Button>
          </Link>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" size="sm" onClick={downloadMd}>
            <Download className="h-4 w-4" /> Markdown
          </Button>
          <Button variant="accent" size="sm" onClick={() => window.print()}>
            <Printer className="h-4 w-4" /> Print / PDF
          </Button>
        </div>
      </div>

      <div className="mb-8 flex items-center gap-3">
        <span className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-ghost-violet to-ghost-indigo">
          <FileText className="h-6 w-6 text-white" />
        </span>
        <div>
          <Badge variant="emerald" className="mb-1">
            Executive Report
          </Badge>
          <h1 className="text-2xl font-bold">{title}</h1>
        </div>
      </div>

      <div className="space-y-5">
        <Section title="Executive Summary">
          <p className="text-sm leading-relaxed text-slate-600">{r.executiveSummary}</p>
          <div className="mt-3 rounded-xl bg-ghost-emerald/10 p-3 text-sm font-medium text-ghost-emerald">
            {r.projectedUplift}
          </div>
        </Section>

        <Section title="Key Findings">
          <Bullets items={r.keyFindings} />
        </Section>

        <div className="grid gap-5 md:grid-cols-2">
          <Section title="Conversion Risks">
            <Bullets items={r.conversionRisks} />
          </Section>
          <Section title="Churn Risks">
            <Bullets items={r.churnRisks} />
          </Section>
          <Section title="Revenue Leaks">
            <Bullets items={r.revenueLeaks} />
          </Section>
          <Section title="Customer Questions">
            <Bullets items={r.customerQuestions} />
          </Section>
        </div>

        <Section title="Competitor Notes">
          <Bullets items={r.competitorNotes} />
        </Section>

        <Section title="Recommendations">
          <div className="space-y-3">
            {r.recommendations.map((rec, i) => (
              <div key={i} className="rounded-xl bg-slate-50 p-4">
                <div className="flex items-start justify-between gap-3">
                  <p className="font-semibold">{rec.title}</p>
                  <div className="flex shrink-0 gap-1.5">
                    <Badge variant="muted">Effort: {rec.effort}</Badge>
                    <Badge variant="emerald">Impact: {rec.impact}</Badge>
                  </div>
                </div>
                <p className="mt-1.5 text-sm text-muted-foreground">{rec.detail}</p>
              </div>
            ))}
          </div>
        </Section>
      </div>
    </div>
  );
}
